### ISSUE TITLE
update TTS docs

### ISSUE THREAD

**Issue by jowodo** [PhidLarkson/Ghana-NLP-Python-Library#1]
Hi, 

this project is amazing! The translations works without problems 🎉 
I tried the `text_to_speech` function as indicated in the [docs in this repo](https://github.com/PhidLarkson/Ghana-NLP-Python-Library?tab=readme-ov-file#text-to-speech-tts), but it seems that it has been renamed to `tts`. 

[In your blog post about this API wrapper](https://pkwolffe.hashnode.dev/ghana-nlp-python-library#heading-text-to-speech-tts), you use the correct function name (`tts`), but imply that the output it an URL instead of binary audio.

**Comment by PhidLarkson** [comment]
Thanks a lot 🎉
I will make those adjustments ASAP
